<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- 机器人底盘参数 -->
  <!-- 定义变量 -->
    <!-- 定义基本单位 -->
    <xacro:property name="mm" value="0.001"/>
    <xacro:property name="cm" value="0.01"/>
    <xacro:property name="g"  value="0.001"/>
    <xacro:property name="kg" value="1.0"/>
    
    <!-- 定义尺寸 -->
    <xacro:property name="ground_offset"     value="${4.5*mm}"/>
    <xacro:property name="base_link_length"  value="${9.1*cm}"/>
    <xacro:property name="base_link_width"   value="${11.2*cm}"/>
    <xacro:property name="base_link_height"  value="${4.4*cm}"/>
    <xacro:property name="wheel_link_length" value="${1.5*cm}"/>
    <xacro:property name="wheel_link_radius" value="${2.2*cm}"/>
    <xacro:property name="wheel_separation"  value="${9.35*cm}"/>
    <xacro:property name="caster_wheel_ball_radius" value="${9*mm}"/>

    <xacro:property name="front_axis" value="${2.5*cm}"/>
    <xacro:property name="rear_axis"  value="${-3.5*cm}"/>

    <!-- 定义重量 -->
    <xacro:property name="mass"              value="${270*g}"/>             
    <xacro:property name="base_mass"         value="${mass*0.8*0.95}"/>  
    <xacro:property name="wheel_mass"        value="${mass*0.2 / 2}"/>         
    <xacro:property name="caster_wheel_mass" value="${mass*0.8*0.05}"/>         


  <!-- 自定义函数 1级 -->
    <!-- 定义几何图形函数 -->
    <xacro:macro name="box" params="length width height">
        <box size="${length} ${width} ${height}"/>
    </xacro:macro>

    <xacro:macro name="wheel" params="length radius">
        <cylinder length="${length}" radius = "${radius}"/>
    </xacro:macro>

    <xacro:macro name="ball" params="radius">
        <sphere radius="${radius}"/>
    </xacro:macro>

    <!-- 定义转动惯量函数 -->
    <xacro:macro name="box_inertia" params="m l w h xyz rpy">
    <inertial>
        <origin xyz="${xyz}" rpy="${rpy}"/>
        <mass value="${m}"/>
        <inertia
        ixx="${(m/12) * (w*w + h*h)}"
        ixy="0" ixz="0"
        iyy="${(m/12) * (l*l + h*h)}"
        iyz="0"
        izz="${(m/12) * (l*l + w*w)}"/>
    </inertial>
    </xacro:macro>

    <xacro:macro name="cylinder_inertia" params="m r h xyz rpy">
        <inertial>
            <origin xyz="${xyz}" rpy="${rpy}"/>
            <mass value="${m}" />
            <inertia ixx="${(m/12) * (3*r*r + h*h)}" ixy="0" ixz="0"
                    iyy="${(m/12) * (3*r*r + h*h)}" iyz="0"
                    izz="${(m/2) * (r*r)}"/>
        </inertial>
    </xacro:macro>





    <!-- 自定义函数 2级 -->
    <!-- 创建主体 -->
    <xacro:macro name="build_base" params="length width height mass">

        <!-- 视觉形状+颜色 -->
        <visual>                                        
            <origin xyz="0 0 ${base_link_height/2 + ground_offset}"  rpy="0 0 0"/>        
            <geometry>                                  
                <xacro:box length="${length}"
                           width="${width}" 
                           height="${height}"/>
            </geometry>                       
            <material name="white"/>                    
        </visual>   

        <!-- 碰撞体积 -->
        <collision>
            <origin xyz="0 0 ${base_link_height/2 + ground_offset}"  rpy="0 0 0"/>        
            <geometry>                                  
                <xacro:box length="${length}"
                           width="${width}" 
                           height="${height}"/>
            </geometry>                           
        </collision>   

        <!-- 惯性 -->
        <xacro:box_inertia m="${mass}"    
                           l="${length}"    
                           w="${width}" 
                           h="${height}"
                           xyz="0 0 ${base_link_height/2 + ground_offset}"
                           rpy="0 0 0" />  

    </xacro:macro>








    <!-- 创建轮子 -->
    <xacro:macro name="build_wheel" params="length radius mass">

        <!-- 视觉形状+颜色 -->
        <visual>                                        
            <origin xyz="0 0 0" rpy="${pi/2.0} 0 0"/>   
            <geometry>                                  
                <xacro:wheel length="${length}" 
                             radius="${radius}"/>
            </geometry>                        
            <material name="black"/>                    
        </visual>    

        <!-- 碰撞体积 -->
        <collision>
            <origin xyz="0 0 0" rpy="${pi/2.0} 0 0"/>   
            <geometry>                                  
                <xacro:wheel length="${length}" 
                             radius="${radius}"/>
            </geometry>                        
        </collision>   

        <!-- 惯性 -->
        <xacro:cylinder_inertia m="${mass}"    
                                r="${radius}"    
                                h="${length}" 
                                xyz="0 0 0"
                                rpy="${pi/2.0} 0 0" />  
     </xacro:macro>

</robot>
