<?xml version="1.0"?>
<robot xmlns:xacro="http://wwww.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="0.091"/>
    <xacro:property name="base_width" value="0.112"/>
    <xacro:property name="base_height" value="0.044"/>
    <xacro:property name="ground_clearance" value="0.0045"/>
    <xacro:property name="caster_wheel_radius" value="${ground_clearance * 2}"/>
    <xacro:property name="wheel_radius" value="${base_height / 2.0}"/>
    <xacro:property name="wheel_width" value="0.015"/>
    <xacro:property name="wheel_offset" value="0.00925"/>
    <xacro:property name="mass" value="0.27"/>
    <xacro:property name="base_mass" value="${mass * 0.8 * 0.95}"/>
    <xacro:property name="caster_wheel_mass" value="${mass * 0.8 * 0.05 }"/>
    <xacro:property name="wheel_mass" value="${mass * 0.1}"/>

    <link name="base_footprint"/>

    <link name="base_link">
        <visual>    
            <origin xyz="-0.0243 0 0"  rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://thymio_mini_project/meshes/base_simple.dae"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="${0.06 - 0.0243} 0 0.009"/>
            <geometry>
              <sphere radius="0.009"/>
            </geometry>
        </collision>
        <collision>    
            <origin xyz="-0.0243 0 0"  rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://thymio_mini_project/meshes/base_collision.dae"/>
            </geometry>
        </collision>
        <xacro:box_inertia m="${base_mass}" l="${base_length}" w="${base_width}" h="${base_height}"
                           xyz="0 0 ${(base_height / 2.0) + ground_clearance}"  rpy="0 0 0" />
    </link>

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <xacro:macro name="wheel_link" params="side">
        <link name="${side}_wheel_link">
            <visual>
                <origin xyz="0 0 0" rpy="${(-pi / 2.0) if side == 'right' else (pi / 2.0)} 0 0"/>
                <geometry>
                    <mesh filename="package://thymio_mini_project/meshes/wheel.dae"/>
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="${(-pi / 2.0) if side == 'right' else (pi / 2.0)} 0 0"/>
                <geometry>
                    <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
                </geometry>
            </collision>
            <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}" 
                                    xyz="0 0 0" rpy="${pi / 2.0} 0 0"/>
        </link>
    </xacro:macro>

    <xacro:wheel_link side="right"/>

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <origin xyz="-0.0243 ${-((base_width / 2.0) - wheel_offset)} ${wheel_radius}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <dynamics damping="0.1" friction="0.2"/>
    </joint>

    <xacro:wheel_link side="left"/>

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <origin xyz="-0.0243 ${((base_width / 2.0) - wheel_offset)} ${wheel_radius}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <dynamics damping="0.1" friction="0.2"/>
    </joint>

</robot>